# Generated by Django 4.2.5 on 2023-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.PositiveIntegerField()),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
