"use client"
import Header from "../components/header"
import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
          <title>Mi App</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
